### ISSUE TITLE
travisCI posts to incorrect slack channel

### ISSUE THREAD

**Issue by RKdev** [watworks/watworks-private-counter-service#2]

**Comment by evillemez** [comment]
Which channel should it be?

**Comment by RKdev** [comment]
It should be posting to the watworks_travisci group - we can try adding it to the .travis.yml file directly, but it might require rebuilding the encrypted token

**Comment by RKdev** [comment]
All the developers were not invited to the watworks-ci private group. When Dev setup TravisCI they could't see the ci channel and pointed travis to the git channel instead.

Fix:
Added Dev team to watworks-ci channel
Rebuilt .travis.yml file using a docker image

docker pull caktux/travis-cli
docker tag caktux/travis-cli travis-cli
docker run --rm -v $PWD:/project travis-cli encrypt "_slack organization name_:_slack api token_" --add notifications.slack.rooms
